name: CI
on: [push, pull_request, workflow_dispatch]
env:
  OPENLOCO_BUILD_SERVER: GitHub
  ASSETS_SSH_KEY: ${{ secrets.ASSETS_SSH_KEY }}
jobs:
  check-code-formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    container:
      image: openrct2/openrct2-build:17-format
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run clang-format
        run: scripts/check-code-formatting.sh
  check-changelog-formatting:
    name: Check changelog formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run check-changelog-formatting
        run: scripts/check-changelog-formatting
  windows:
    name: Windows x64 (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    needs: check-code-formatting
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            preset: windows
            build_preset: windows-release
            build_dir: windows
          - os: windows-2025
            preset: windows2026
            build_preset: windows2026-release
            build_dir: windows2026
    env:
      CONFIGURATION: Release
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup cache env vars
        run: |
          echo "VCPKG_DEFAULT_BINARY_CACHE=${{ github.workspace }}/vcpkg-cache" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Setup cache directories
        run: mkdir ${{ env.VCPKG_DEFAULT_BINARY_CACHE }} | Out-Null
      - name: Set up binary cache
        uses: actions/cache@v5
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: ${{ matrix.os }}-64-vcpkg-${{ env.ImageVersion }}-${{ hashFiles('vcpkg*.json') }}
          restore-keys: |
            ${{ matrix.os }}-64-vcpkg-${{ env.ImageVersion }}-
      - name: Build OpenLoco
        shell: cmd
        run: |
          cmake --preset ${{ matrix.preset }}
          cmake --build --preset ${{ matrix.build_preset }}
      - name: Build release
        run: |
          mkdir artifacts | Out-Null
          Copy-Item CHANGELOG.md,CONTRIBUTORS.md,LICENSE artifacts
          Copy-Item build\${{ matrix.build_dir }}\Release\* artifacts -Recurse
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenLoco-${{ matrix.os }}-x64
          path: |
            artifacts/
            !artifacts/*.pdb
          if-no-files-found: error
      - name: Upload symbols artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenLoco-${{ matrix.os }}-x64-symbols
          path: |
            artifacts/*.pdb
          if-no-files-found: warn
      - name: Checkout Assets
        if: ${{ github.repository == 'OpenLoco/OpenLoco' && env.ASSETS_SSH_KEY != null }}
        uses: actions/checkout@v6
        with:
          ssh-key: ${{ env.ASSETS_SSH_KEY }}
          repository: OpenLoco/LocomotionAssets
          ref: gog
          path: LocomotionAssets
      - name: Checkout Test Data
        if: ${{ github.repository == 'OpenLoco/OpenLoco' && env.ASSETS_SSH_KEY != null }}
        uses: actions/checkout@v6
        with:
          repository: OpenLoco/TestData
          ref: a4328bfa3c7f1df7a2e690baade0af181929b0b4
          path: TestData
      - name: Run Simulate Test
        if: ${{ github.repository == 'OpenLoco/OpenLoco' && env.ASSETS_SSH_KEY != null }}
        shell: bash
        run: |
          set -e
          ./build/${{ matrix.build_dir }}/Release/OpenLoco.exe --locomotion_path "./LocomotionAssets" simulate "./TestData/Saves/MMTest.SV5" 100000 -o "result.sv5"
          ./build/${{ matrix.build_dir }}/Release/OpenLoco.exe --locomotion_path "./LocomotionAssets" compare "./TestData/Saves/MMTest100000_base.SV5" "result.sv5"
      - name: Run Tests
        shell: cmd
        run: |
          ctest --test-dir build\${{ matrix.build_dir }}\ --output-on-failure
  windows32:
    name: Windows Win32
    runs-on: windows-2022
    needs: check-code-formatting
    env:
      CONFIGURATION: Release
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup cache env vars
        run: |
          echo "VCPKG_DEFAULT_BINARY_CACHE=${{ github.workspace }}/vcpkg-cache" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Setup cache directories
        run: mkdir ${{ env.VCPKG_DEFAULT_BINARY_CACHE }} | Out-Null
      - name: Set up binary cache
        uses: actions/cache@v5
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: ${{ runner.os }}-32-vcpkg-${{ env.ImageVersion }}-${{ hashFiles('vcpkg*.json') }}
          restore-keys: |
            ${{ runner.os }}-32-vcpkg-${{ env.ImageVersion }}-
      - name: Build OpenLoco
        shell: cmd
        run: |
          cmake --preset windows-x86-32-ci
          cmake --build --preset windows-x86-32-ci
      - name: Build release
        run: |
          mkdir artifacts | Out-Null
          Copy-Item CHANGELOG.md,CONTRIBUTORS.md,LICENSE artifacts
          Copy-Item build\windows-x86-32-ci\Release\* artifacts -Recurse
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenLoco-${{ runner.os }}-Win32
          path: |
            artifacts/
            !artifacts/*.pdb
          if-no-files-found: error
      - name: Upload symbols artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenLoco-${{ runner.os }}-Win32-symbols
          path: |
            artifacts/*.pdb
          if-no-files-found: warn
      - name: Run Tests
        shell: cmd
        run: |
          ctest --test-dir build\windows-x86-32-ci\ --output-on-failure
